[package]
name = "fs2"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "An alternative to std::fs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
